name: Deploy Angular

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node 12.x
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install dependencies
        run: |
          npm install
          npm run build
          ls -l    
          
      - name: copy file via ssh key
        uses: appleboy/scp-action@master
        with:
          host: 103.137.194.167
          username: gloryauto
          password: ${{ secrets.GFL_P_PASSWORD }}
          source: "dist"
          target: "GFL_FE"
          
      - name: SSH Remote Commands
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: 103.137.194.167
          username: gloryauto
          password: ${{ secrets.GFL_P_PASSWORD }}
          script: |
            sudo systemctl restart nginx
            
    
