name: Deploy Angular

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node 12.x
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install dependencies
        run: |
          npm install
          npm run build
          ls -l    
          
      - name: copy file via ssh key
        uses: appleboy/scp-action@master
        with:
          host: 13.235.71.124
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          source: "dist"
          target: "GFL_FE"
          
      - name: SSH Remote Commands
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: 13.235.71.124
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          script: |
            sudo systemctl restart nginx
            
      - name: slack the message for success
        if: success()
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":"Front end pipeline succeeded"}' https://hooks.slack.com/services/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
      
      - name: slack the message for faliure
        if: failure()
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":"Front end pipeline failed"}' https://hooks.slack.com/services/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
          
          
